### PR TITLE
#344 Ignore RESCOPED event without any changes to target PR

### PR DESCRIPTION
**Pull request by madisparn**
Should reduce noise introduced in #277 and solve part of #344

### CODE REVIEW

**Comment by madisparn** [comment]
@mvlasovatl Does this look like something useful?

**Comment by mvlasovatl** [comment]
I switched to other tasks for a while. @YevhenHrytsai will be the main supporter of this repo now.

**Comment by madisparn** [comment]
@YevhenHrytsai Could you review the changes?

**Comment by YevhenHrytsai** [comment]
> @YevhenHrytsai Could you review the changes?

Sure, will review

**Comment by madisparn** [comment]
@YevhenHrytsai Do you have any ETA when you can get to it? The re-scoped slack notifications are quite regular and annoying.

**Review by YevhenHrytsai — APPROVED** [review]

**Comment by YevhenHrytsai** [comment]
@madisparn sorry for delay
Merging and will make a release

**Comment by madisparn** [comment]
> @madisparn sorry for delay Merging and will make a release

Thank you

**Comment by eddyg** [comment]
Any idea when a new release will be available that suppresses the "re-scope pulled request" notifications?

**Comment by YevhenHrytsai** [comment]
Version `4.0.10` with these changes is available on the Marketplace
[Bitbucket Data Center for Slack](https://marketplace.atlassian.com/apps/1220729/bitbucket-data-center-for-slack-official?tab=versions&hosting=datacenter)

**Pull request merged**
