### PR TITLE
Jira: Filter for the notifier collection

### PR DESCRIPTION
**Pull request by gonchik**
Hi! 

As I see better remove from list of notifiers inactive and null/inactive users.
It's related to the #36

Cheers,
Gonchik Tsymzhitov

### CODE REVIEW

**Comment by gonchik** [comment]
@sethgho What's the procedure of bugfix? I will be happy to go merge it

**Comment by sethgho** [comment]
Hi @gonchik. I don't have anyone actively working on this project at the moment. At a minimum, we'll triage this repo fortnightly. We'll take a look by end of week.

**Comment by sethgho** [comment]
Hmm. Looks like we'll need to address #32 to get tests running for PRs from forks before we can merge this.

**Review by mvlasovatl — APPROVED** [review]

**Comment by mvlasovatl** [comment]
Thanks for the contribution, Gonchik! This fix will be included into the next release of Jira Server for Slack plugin.

**Pull request merged**
